development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/2" } %>
  channel_prefix: zlecajto_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDISCLOUD_URL") %>
  channel_prefix: zlecajto_production
